//
//  UIColor.swift
//  doit
//
//  Copyright © 2019 Depromeet. All rights reserved.
//

import UIKit

extension UIColor {
    
    var hexString: String {
        
        var r: CGFloat = 0
        var g: CGFloat = 0
        var b: CGFloat = 0
        var a: CGFloat = 0
        
        getRed(&r, green: &g, blue: &b, alpha: &a)
        
        let rgb: Int = (Int)(r * 255) << 16 | (Int)(g * 255) << 8 | (Int)(b * 255) << 0
        
        return String(format: "#%06x", rgb)
    }
    
    convenience init(red: Int, green: Int, blue: Int, opacity: CGFloat = 1.0) {
        assert(red >= 0 && red <= 255, "Invalid red component")
        assert(green >= 0 && green <= 255, "Invalid green component")
        assert(blue >= 0 && blue <= 255, "Invalid blue component")
        self.init(red: CGFloat(red) / 255.0, green: CGFloat(green) / 255.0, blue: CGFloat(blue) / 255.0, alpha: opacity)
    }
    
    convenience init(hexString: String, alpha: CGFloat = 1.0) {
        var hexInt: UInt32 = 0
        let scanner = Scanner(string: hexString)
        scanner.charactersToBeSkipped = CharacterSet(charactersIn: "#")
        scanner.scanHexInt32(&hexInt)
        
        let red = CGFloat((hexInt & 0xff0000) >> 16) / 255.0
        let green = CGFloat((hexInt & 0xff00) >> 8) / 255.0
        let blue = CGFloat((hexInt & 0xff) >> 0) / 255.0
        let alpha = alpha
        
        self.init(red: red, green: green, blue: blue, alpha: alpha)
    }
}

// Color palette
// Auto generated by Zeplin
extension UIColor {
    
    @nonobjc class var warmGrey: UIColor {
        return UIColor(white: 151.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var black: UIColor {
        return UIColor(white: 34.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var white: UIColor {
        return UIColor(white: 1.0, alpha: 1.0)
    }
    
    @nonobjc class var burple: UIColor {
        return UIColor(red: 119.0 / 255.0, green: 29.0 / 255.0, blue: 228.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var blackTwo: UIColor {
        return UIColor(white: 40.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var darkGrey: UIColor {
        return UIColor(red: 40.0 / 255.0, green: 41.0 / 255.0, blue: 42.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var mediumGreen: UIColor {
        return UIColor(red: 46.0 / 255.0, green: 177.0 / 255.0, blue: 68.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var kiwiGreen: UIColor {
        return UIColor(red: 138.0 / 255.0, green: 221.0 / 255.0, blue: 75.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var offWhite: UIColor {
        return UIColor(red: 1.0, green: 1.0, blue: 240.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var dodgerBlue: UIColor {
        return UIColor(red: 77.0 / 255.0, green: 144.0 / 255.0, blue: 251.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var blackThree: UIColor {
        return UIColor(white: 43.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var brownishGrey: UIColor {
        return UIColor(white: 119.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var veryLightPink: UIColor {
        return UIColor(white: 221.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var veryLightPinkTwo: UIColor {
        return UIColor(white: 196.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var darkishPink: UIColor {
        return UIColor(red: 245.0 / 255.0, green: 49.0 / 255.0, blue: 127.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var salmon: UIColor {
        return UIColor(red: 1.0, green: 120.0 / 255.0, blue: 106.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var dustyOrange: UIColor {
        return UIColor(red: 242.0 / 255.0, green: 106.0 / 255.0, blue: 60.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var goldenYellow: UIColor {
        return UIColor(red: 242.0 / 255.0, green: 208.0 / 255.0, blue: 38.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var turquoiseBlue: UIColor {
        return UIColor(red: 8.0 / 255.0, green: 186.0 / 255.0, blue: 195.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var greenishCyan: UIColor {
        return UIColor(red: 61.0 / 255.0, green: 235.0 / 255.0, blue: 165.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var clearBlue: UIColor {
        return UIColor(red: 28.0 / 255.0, green: 135.0 / 255.0, blue: 1.0, alpha: 1.0)
    }
    
    @nonobjc class var weirdGreen: UIColor {
        return UIColor(red: 52.0 / 255.0, green: 246.0 / 255.0, blue: 135.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var clearBlueTwo: UIColor {
        return UIColor(red: 28.0 / 255.0, green: 116.0 / 255.0, blue: 224.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var brightCyan: UIColor {
        return UIColor(red: 77.0 / 255.0, green: 197.0 / 255.0, blue: 247.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var violet: UIColor {
        return UIColor(red: 156.0 / 255.0, green: 19.0 / 255.0, blue: 205.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var candyPink: UIColor {
        return UIColor(red: 1.0, green: 99.0 / 255.0, blue: 222.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var softBlue: UIColor {
        return UIColor(red: 81.0 / 255.0, green: 136.0 / 255.0, blue: 250.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var purplyBlue: UIColor {
        return UIColor(red: 117.0 / 255.0, green: 38.0 / 255.0, blue: 230.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var blackFour: UIColor {
        return UIColor(white: 25.0 / 255.0, alpha: 1.0)
    }
    
    @nonobjc class var blackFive: UIColor {
        return UIColor(white: 51.0 / 255.0, alpha: 1.0)
    }
    
}
