//
//  UIFont.swift
//  doit
//
//  Copyright © 2019 Depromeet. All rights reserved.
//

// Text styles
// Auto generated by Zeplin
extension UIFont {
    class var title1: UIFont {
        return UIFont.systemFont(ofSize: 30.0, weight: .bold)
    }
    
    class var goalCardTitle: UIFont {
        return UIFont.systemFont(ofSize: 24.0, weight: .bold)
    }
    
    class var goalCardDescription: UIFont {
        return UIFont.systemFont(ofSize: 14, weight: .regular)
    }
}
